ci: fix workflow file
Signed-off-by: PavelSBorisov <pavel.s.borisov@gmail.com>

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -7,8 +7,13 @@ on:
       - main
   workflow_dispatch:
     inputs:
+      branch:
+        description: "Github branch (should always be main unless testing workflow changes) to release from:"
+        type: string
+        required: false
+        default: "main"
       dry-run-enabled:
-        description: "Perform Dry Run"
+        description: "Perform Dry Run (Checks new semantic release version and confirms gradle assemble is successful):"
         type: boolean
         required: false
         default: false
@@ -45,144 +50,60 @@ env:
   GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}
 
 jobs:
-  prepare-release:
-    name: Release / Prepare
-    runs-on: network-node-linux-medium
-    outputs:
-      version: ${{ steps.tag.outputs.version }}
-    steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
-        with:
-          egress-policy: audit
+  # prepare-release:
+  #   name: Release / Prepare
+  #   runs-on: network-node-linux-medium
+  #   outputs:
+  #     version: ${{ steps.tag.outputs.version }}
+  #   steps:
+  #     - name: Harden Runner
+  #       uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
+  #       with:
+  #         egress-policy: audit
 
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          token: ${{ secrets.GH_ACCESS_TOKEN }}
-          fetch-depth: 0
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #       with:
+  #         token: ${{ secrets.GH_ACCESS_TOKEN }}
+  #         fetch-depth: 0
+  #         ref: ${{ github.event.inputs.branch }}
 
-      - name: Setup Node
-        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
-        with:
-          node-version: 20.18.0
+  #     - name: Setup Node
+  #       uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
+  #       with:
+  #         node-version: 20.18.0
 
-      - name: Install Semantic Release
-        run: |
-          npm install -g semantic-release@21.0.7 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3 gradle-semantic-release-plugin@1.7.6
-          npm install -g conventional-changelog-conventionalcommits@6.1.0 @commitlint/cli@17.6.6 @commitlint/config-conventional@17.6.6
-          npm install -g marked-mangle@1.0.1 marked-gfm-heading-id@3.0.4 semantic-release-conventional-commits@3.0.0
+  #     - name: Install Semantic Release
+  #       run: |
+  #         npm install -g semantic-release@21.0.7 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3 gradle-semantic-release-plugin@1.7.6
+  #         npm install -g conventional-changelog-conventionalcommits@6.1.0 @commitlint/cli@17.6.6 @commitlint/config-conventional@17.6.6
+  #         npm install -g marked-mangle@1.0.1 marked-gfm-heading-id@3.0.4 semantic-release-conventional-commits@3.0.0
 
-      - name: Calculate Next Version
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER_NAME }}
-          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-          GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
-          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-        run: |
-          npx semantic-release --dry-run
-          ls -al
-          cat VERSION
+  #     - name: Calculate Next Version
+  #       env:
+  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         GIT_AUTHOR_NAME: ${{ secrets.GIT_USER_NAME }}
+  #         GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
+  #         GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
+  #         GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
+  #       run: |
+  #         npx semantic-release --dry-run
+  #         ls -al
+  #         cat VERSION
 
-      - name: Extract Version
-        id: tag
-        run: |
-          cat VERSION
-          [[ "${{ github.event.inputs.dry-run-enabled }}" == true && ! -f VERSION ]] && echo -n "0.0.0-latest" > VERSION
-          echo "version=$(cat VERSION | tr -d '[:space:]')" | tee -a ${GITHUB_OUTPUT}
-
-  publish-maven-central:
-    name: Publish Maven Central
-    runs-on: network-node-linux-medium
-    needs:
-      - prepare-release
-    steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
-        with:
-          egress-policy: audit
-
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          fetch-depth: 0
-
-      # This step is required for some self-hosted runners because the default gpg does not include the gpg2 command.
-      - name: Install GnuPG Tools
-        run: |
-          if ! command -v gpg2 >/dev/null 2>&1; then
-            echo "::group::Updating APT Repository Indices"
-              sudo apt update
-            echo "::endgroup::"
-            echo "::group::Installing GnuPG Tools"
-              sudo apt install -y gnupg2
-            echo "::endgroup::"
-          fi
-
-      - name: Import GPG key
-        id: gpg_key
-        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v.6.1.0
-        if: ${{ github.event.inputs.dry-run-enabled != true && !cancelled() && !failure() }}
-        with:
-          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
-          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
-          git_config_global: true
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-          git_tag_gpgsign: true
-
-      - name: Setup Java
-        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
-        with:
-          distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
-          java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
-        with:
-          gradle-version: wrapper
-
-      # This step is used to update the version number in the version.txt file.
-      - name: Apply Version Number Update (Explicit)
-        run: ./gradlew versionAsSpecified -PnewVersion=${{ needs.prepare-release.outputs.version }}
-
-      # Technically, this step is not required but is executed to provide the end users with a summary of the version
-      # numbers assigned to each published artifact.
-      - name: Version Report
-        run: ./gradlew githubVersionSummary
-
-      # Technically, this step is not required because the release steps will build what is required; however,
-      # if one or more components fails to build then it could result in a partial publish to Maven Central.
-      # The inclusion of this step ensures the job fails cleanly without publishing to Maven Central if any of the
-      # components fail to build.
-      - name: Gradle Assemble
-        id: gradle-build
-        if: ${{ github.event.inputs.dry-run-enabled != true && !cancelled() && !failure() }}
-        run: ./gradlew assemble
-
-      # Publishes the artifacts to the Maven Central Nexus staging repository.
-      # TODO for initial release and testing, we use -PpublishTestRelease to not automatically release from staging.
-      - name: Gradle Publish to Maven Central - common
-        if: ${{ github.event.inputs.dry-run-enabled != true && !cancelled() && !failure() }}
-        env:
-          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USER_NAME }}
-          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_USER_PASSWORD }}
-        run: ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.common -PpublishSigningEnabled=true --no-configuration-cache -PpublishTestRelease=true
-
-      - name: Gradle Publish to Maven Central - cryptography
-        if: ${{ github.event.inputs.dry-run-enabled != true && !cancelled() && !failure() }}
-        env:
-          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USER_NAME }}
-          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_USER_PASSWORD }}
-        run: ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.cryptography -PpublishSigningEnabled=true --no-configuration-cache -PpublishTestRelease=true
+  #     - name: Extract Version
+  #       id: tag
+  #       run: |
+  #         cat VERSION
+  #         [[ "${{ github.event.inputs.dry-run-enabled }}" == true && ! -f VERSION ]] && echo -n "0.0.0-latest" > VERSION
+  #         echo "version=$(cat VERSION | tr -d '[:space:]')" | tee -a ${GITHUB_OUTPUT}
 
   create-github-release:
     name: Github / Release
     runs-on: network-node-linux-medium
-    needs:
-      - publish-maven-central
+    # Only run this job for official releases (workflow_dispatch) and not for snapshot releases (push to main)
+    if: ${{ github.event_name == 'workflow_dispatch' && !cancelled() && !failure() }}
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
@@ -194,6 +115,7 @@ jobs:
         with:
           token: ${{ secrets.GH_ACCESS_TOKEN }}
           fetch-depth: 0
+          ref: ${{ github.event.inputs.branch }}
 
       - name: Install GnuPG Tools
         run: |
@@ -229,7 +151,7 @@ jobs:
           gradle-version: wrapper
 
       - name: Setup Node
-        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
+        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
         with:
           node-version: 20.18.0
 
@@ -247,5 +169,109 @@ jobs:
           GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
           GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
           GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
+        run: |
+          if [[ "${{ github.event.inputs.dry-run-enabled }}" == "true" ]]; then
+            echo "Running semantic-release in dry-run mode"
+            npx semantic-release --dry-run
+          else
+            echo "Running semantic-release to create a release"
+            npx semantic-release
+          fi
+
+  publish-maven-central:
+    name: Publish Maven Central
+    runs-on: network-node-linux-medium
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
+        with:
+          egress-policy: audit
+
+      - name: Checkout Code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.inputs.branch }}
+
+      # This step is required for some self-hosted runners because the default gpg does not include the gpg2 command.
+      - name: Install GnuPG Tools
+        if: ${{ !cancelled() && !failure() }}
+        run: |
+          if ! command -v gpg2 >/dev/null 2>&1; then
+            echo "::group::Updating APT Repository Indices"
+              sudo apt update
+            echo "::endgroup::"
+            echo "::group::Installing GnuPG Tools"
+              sudo apt install -y gnupg2
+            echo "::endgroup::"
+          fi
+
+      - name: Import GPG key
+        id: gpg_key
+        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v.6.1.0
+        if: ${{ !cancelled() && !failure() }}
+        with:
+          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
+          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
+          git_config_global: true
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+          git_tag_gpgsign: true
+
+      - name: Setup Java
+        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
+        if: ${{ !cancelled() && !failure() }}
+        with:
+          distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
+          java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
+        if: ${{ !cancelled() && !failure() }}
+        with:
+          gradle-version: wrapper
+
+      # This step updates the version number to a snapshot in version.txt when publishing a snapshot release.
+      - name: Add SNAPSHOT Suffix to Current Version
+        if: ${{ github.event_name == 'push' && !cancelled() && !failure() }}
+        run: ./gradlew versionAsSnapshot
+
+      # Technically, this step is not required but is executed to provide the end users with a summary of the version
+      # numbers assigned to each published artifact.
+      - name: Version Report
+        if: ${{ !cancelled() && !failure() }}
+        run: ./gradlew githubVersionSummary
+
+      # Technically, this step is not required because the release steps will build what is required; however,
+      # if one or more components fails to build then it could result in a partial publish to Maven Central.
+      # The inclusion of this step ensures the job fails cleanly without publishing to Maven Central if any of the
+      # components fail to build.
+      - name: Gradle Assemble
+        if: ${{ !cancelled() && !failure() }}
+        run: ./gradlew assemble
+
+      # Publishes the artifacts to the Maven Central Nexus staging repository.
+      # Set publishTestRelease=true for snapshot releases (push to main), and omit for official releases (workflow_dispatch)
+      - name: Gradle Publish to Maven Central - common
         if: ${{ github.event.inputs.dry-run-enabled != 'true' && !cancelled() && !failure() }}
-        run: npx semantic-release
+        env:
+          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USER_NAME }}
+          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_USER_PASSWORD }}
+        run: |
+          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
+            ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.common -PpublishSigningEnabled=true --no-configuration-cache -PpublishTestRelease=true
+          else
+            ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.common -PpublishSigningEnabled=true --no-configuration-cache
+          fi
+
+      - name: Gradle Publish to Maven Central - cryptography
+        if: ${{ github.event.inputs.dry-run-enabled != 'true' && !cancelled() && !failure() }}
+        env:
+          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USER_NAME }}
+          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_USER_PASSWORD }}
+        run: |
+          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
+            ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.cryptography -PpublishSigningEnabled=true --no-configuration-cache -PpublishTestRelease=true
+          else
+            ./gradlew releaseMavenCentral -PpublishingPackageGroup=com.hedera.cryptography -PpublishSigningEnabled=true --no-configuration-cache
+          fi
