ci: Create a testing commit for easy maven central publishing practice
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -114,74 +114,74 @@ jobs:
       ossrh-user-name: ${{ secrets.SVCS_OSSRH_USER_NAME }}
       ossrh-user-password: ${{ secrets.SVCS_OSSRH_USER_PASSWORD }}
 
-  create-github-release:
-    name: Github / Release
-    runs-on: network-node-linux-medium
-    needs:
-      - publish-maven-central
-    steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
-        with:
-          egress-policy: audit
-
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          token: ${{ secrets.GH_ACCESS_TOKEN }}
-          fetch-depth: 0
-
-      - name: Install GnuPG Tools
-        run: |
-          if ! command -v gpg2 >/dev/null 2>&1; then
-            echo "::group::Updating APT Repository Indices"
-              sudo apt update
-            echo "::endgroup::"
-            echo "::group::Installing GnuPG Tools"
-              sudo apt install -y gnupg2
-            echo "::endgroup::"
-          fi
-
-      - name: Import GPG key
-        id: gpg_key
-        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v.6.1.0
-        with:
-          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
-          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
-          git_config_global: true
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-          git_tag_gpgsign: false
-
-      - name: Setup Java
-        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
-        with:
-          distribution: ${{ inputs.java-distribution }}
-          java-version: ${{ inputs.java-version }}
-
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
-        with:
-          gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
-
-      - name: Setup Node
-        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
-        with:
-          node-version: 20.18.0
-
-      - name: Install Semantic Release
-        run: |
-          npm install -g semantic-release@21.0.7 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3 gradle-semantic-release-plugin@1.7.6
-          npm install -g conventional-changelog-conventionalcommits@6.1.0 @commitlint/cli@17.6.6 @commitlint/config-conventional@17.6.6
-          npm install -g marked-mangle@1.0.1 marked-gfm-heading-id@3.0.4 semantic-release-conventional-commits@3.0.0
-
-      - name: Publish Semantic Release
-        env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
-          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER_NAME }}
-          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-          GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
-          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-        if: ${{ github.event.inputs.dry-run-enabled != 'true' && !cancelled() && !failure() }}
-        run: npx semantic-release
+#  create-github-release:
+#    name: Github / Release
+#    runs-on: network-node-linux-medium
+#    needs:
+#      - publish-maven-central
+#    steps:
+#      - name: Harden Runner
+#        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
+#        with:
+#          egress-policy: audit
+#
+#      - name: Checkout Code
+#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+#        with:
+#          token: ${{ secrets.GH_ACCESS_TOKEN }}
+#          fetch-depth: 0
+#
+#      - name: Install GnuPG Tools
+#        run: |
+#          if ! command -v gpg2 >/dev/null 2>&1; then
+#            echo "::group::Updating APT Repository Indices"
+#              sudo apt update
+#            echo "::endgroup::"
+#            echo "::group::Installing GnuPG Tools"
+#              sudo apt install -y gnupg2
+#            echo "::endgroup::"
+#          fi
+#
+#      - name: Import GPG key
+#        id: gpg_key
+#        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v.6.1.0
+#        with:
+#          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
+#          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
+#          git_config_global: true
+#          git_user_signingkey: true
+#          git_commit_gpgsign: true
+#          git_tag_gpgsign: false
+#
+#      - name: Setup Java
+#        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
+#        with:
+#          distribution: ${{ inputs.java-distribution }}
+#          java-version: ${{ inputs.java-version }}
+#
+#      - name: Setup Gradle
+#        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
+#        with:
+#          gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
+#
+#      - name: Setup Node
+#        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
+#        with:
+#          node-version: 20.18.0
+#
+#      - name: Install Semantic Release
+#        run: |
+#          npm install -g semantic-release@21.0.7 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3 gradle-semantic-release-plugin@1.7.6
+#          npm install -g conventional-changelog-conventionalcommits@6.1.0 @commitlint/cli@17.6.6 @commitlint/config-conventional@17.6.6
+#          npm install -g marked-mangle@1.0.1 marked-gfm-heading-id@3.0.4 semantic-release-conventional-commits@3.0.0
+#
+#      - name: Publish Semantic Release
+#        env:
+#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+#          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
+#          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER_NAME }}
+#          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
+#          GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
+#          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
+#        if: ${{ github.event.inputs.dry-run-enabled != 'true' && !cancelled() && !failure() }}
+#        run: npx semantic-release
